[tool.isort]
# Black compatible values for isort https://black.readthedocs.io/en/stable/compatible_configs.html#isort
profile = "black"

[tool.pytest.ini_options]
addopts = "-v --cov=grm --cov-report html"
testpaths = "tests"