# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Drainage
                                 A QGIS plugin
  
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-13
        copyright            : (C) 2019 by KICT, Hermesys
        email                : info@hermesys.co.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from qgis.utils import iface
from .drainage import Drainage


# noinspection PyPep8Naming
def class_factory(iface):  # pylint: disable=invalid-name
    """Load Drainage class from file Drainage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    return Drainage(iface)
